const { normalizeName } = require("../utils/normalizers");

const mockBusinesses = [
  {
    name: "Casa Meridian Realty",
    city: "Merida",
    email: "contacto@casameridian.com",
    phone: "9992451101",
    type: "Inmobiliaria",
    website: "",
    rating: "4.7",
    websiteStatus: "sin-sitio",
    source: "mock:merida-realty-list",
  },
  {
    name: "Bistro Norte 47",
    city: "Merida",
    email: "hola@bistronorte47.mx",
    phone: "9993104502",
    type: "Restaurante",
    website: "https://instagram.com/bistronorte47",
    rating: "4.5",
    websiteStatus: "solo-redes",
    source: "mock:merida-food-guide",
  },
  {
    name: "Clinica Santa Lucia",
    city: "Merida",
    email: "recepcion@clinicasantalucia.mx",
    phone: "9991127840",
    type: "Clinica",
    website: "https://clinicasantalucia.wixsite.com/merida",
    rating: "4.4",
    websiteStatus: "sitio-basico",
    source: "mock:merida-health-directory",
  },
  {
    name: "Taller Creativo Itza",
    city: "Merida",
    email: "hola@talleritza.mx",
    phone: "9998705544",
    type: "Estudio",
    website: "",
    rating: "4.8",
    websiteStatus: "sin-sitio",
    source: "mock:merida-local-businesses",
  },
  {
    name: "Mar y Lena Cocina del Grijalva",
    city: "Villahermosa",
    email: "reservas@marylena.mx",
    phone: "9934129981",
    type: "Restaurante",
    website: "",
    rating: "4.6",
    websiteStatus: "sin-sitio",
    source: "mock:villahermosa-food-guide",
  },
  {
    name: "Inmuebles Tabasco Centro",
    city: "Villahermosa",
    email: "asesoria@inmueblestabasco.com",
    phone: "9932671105",
    type: "Inmobiliaria",
    website: "https://inmueblestabasco-centro.ueniweb.com",
    rating: "4.3",
    websiteStatus: "sitio-basico",
    source: "mock:villahermosa-property-guide",
  },
  {
    name: "Clinica Integral Olmeca",
    city: "Villahermosa",
    email: "info@olmecasalud.mx",
    phone: "9935120084",
    type: "Clinica",
    website: "https://facebook.com/olmecasalud",
    rating: "4.2",
    websiteStatus: "solo-redes",
    source: "mock:villahermosa-health-directory",
  },
  {
    name: "Optica La Ceiba",
    city: "Villahermosa",
    email: "contacto@opticalaceiba.mx",
    phone: "9936014470",
    type: "Optica",
    website: "",
    rating: "4.5",
    websiteStatus: "sin-sitio",
    source: "mock:villahermosa-local-businesses",
  },
  {
    name: "Roma Habitat Inmobiliaria",
    city: "Ciudad de Mexico",
    email: "ventas@romahabitat.mx",
    phone: "5556449210",
    type: "Inmobiliaria",
    website: "",
    rating: "4.4",
    websiteStatus: "sin-sitio",
    source: "mock:cdmx-property-leads",
  },
  {
    name: "Comedor Xola",
    city: "Ciudad de Mexico",
    email: "hola@comedorxola.mx",
    phone: "5559981402",
    type: "Restaurante",
    website: "https://facebook.com/comedorxola",
    rating: "4.4",
    websiteStatus: "solo-redes",
    source: "mock:cdmx-food-guide",
  },
  {
    name: "Dental Narvarte Uno",
    city: "Ciudad de Mexico",
    email: "citas@dentalnarvarteuno.mx",
    phone: "5551007741",
    type: "Clinica",
    website: "https://dentalnarvarteuno.wixsite.com/home",
    rating: "4.7",
    websiteStatus: "sitio-basico",
    source: "mock:cdmx-health-directory",
  },
  {
    name: "Estudio Contable Reforma",
    city: "Ciudad de Mexico",
    email: "info@ec-reforma.mx",
    phone: "5557003384",
    type: "Despacho",
    website: "",
    rating: "4.5",
    websiteStatus: "sin-sitio",
    source: "mock:cdmx-local-services",
  },
  {
    name: "Los Almendros Restaurante",
    city: "Merida",
    email: "paracontactarnos@losalmendros.com.mx",
    phone: "9999421111",
    type: "Restaurante",
    website: "https://losalmendros.com.mx",
    rating: "4.6",
    websiteStatus: "sitio-antiguo",
    source: "mock:duplicate-check",
  },
  {
    name: "Yucatan Properties",
    city: "Merida",
    email: "mj@semerena.com",
    phone: "9999484444",
    type: "Inmobiliaria",
    website: "https://yucatanproperties.com",
    rating: "4.6",
    websiteStatus: "sitio-antiguo",
    source: "mock:duplicate-check",
  },
  {
    name: "Aurea Patrimonio",
    city: "Merida",
    email: "contacto@aureapatrimonio.mx",
    phone: "9993320041",
    type: "Inmobiliaria",
    website: "",
    rating: "4.5",
    websiteStatus: "sin-sitio",
    source: "mock:merida-realty-list",
  },
  {
    name: "Patio Sabor Maya",
    city: "Merida",
    email: "hola@patiosabormaya.mx",
    phone: "9994502273",
    type: "Restaurante",
    website: "https://facebook.com/patiosabormaya",
    rating: "4.6",
    websiteStatus: "solo-redes",
    source: "mock:merida-food-guide",
  },
  {
    name: "Centro Medico Itzimna",
    city: "Merida",
    email: "citas@cmitzimna.mx",
    phone: "9995013378",
    type: "Clinica",
    website: "",
    rating: "4.3",
    websiteStatus: "sin-sitio",
    source: "mock:merida-health-directory",
  },
  {
    name: "Estudio Contable Montejo",
    city: "Merida",
    email: "info@ecmontejo.mx",
    phone: "9996401152",
    type: "Despacho",
    website: "",
    rating: "4.7",
    websiteStatus: "sin-sitio",
    source: "mock:merida-local-businesses",
  },
  {
    name: "Raiz Sureste Bienes Raices",
    city: "Villahermosa",
    email: "asesores@raizsureste.mx",
    phone: "9931884022",
    type: "Inmobiliaria",
    website: "",
    rating: "4.4",
    websiteStatus: "sin-sitio",
    source: "mock:villahermosa-property-guide",
  },
  {
    name: "Fogon del Malecon",
    city: "Villahermosa",
    email: "reservas@fogondelmalecon.mx",
    phone: "9937001841",
    type: "Restaurante",
    website: "",
    rating: "4.5",
    websiteStatus: "sin-sitio",
    source: "mock:villahermosa-food-guide",
  },
  {
    name: "Clinica Familiar Guayacan",
    city: "Villahermosa",
    email: "hola@guayacansalud.mx",
    phone: "9938205511",
    type: "Clinica",
    website: "https://facebook.com/guayacansalud",
    rating: "4.1",
    websiteStatus: "solo-redes",
    source: "mock:villahermosa-health-directory",
  },
  {
    name: "Optica Centro Tabasco",
    city: "Villahermosa",
    email: "vision@opticacentrotabasco.mx",
    phone: "9939048842",
    type: "Optica",
    website: "",
    rating: "4.6",
    websiteStatus: "sin-sitio",
    source: "mock:villahermosa-local-businesses",
  },
  {
    name: "Vertical Homes CDMX",
    city: "Ciudad de Mexico",
    email: "ventas@verticalhomes.mx",
    phone: "5560124481",
    type: "Inmobiliaria",
    website: "",
    rating: "4.5",
    websiteStatus: "sin-sitio",
    source: "mock:cdmx-property-leads",
  },
  {
    name: "Mesa Insurgentes",
    city: "Ciudad de Mexico",
    email: "hola@mesainsurgentes.mx",
    phone: "5561409923",
    type: "Restaurante",
    website: "https://instagram.com/mesainsurgentes",
    rating: "4.3",
    websiteStatus: "solo-redes",
    source: "mock:cdmx-food-guide",
  },
  {
    name: "Clinica Roma Norte",
    city: "Ciudad de Mexico",
    email: "citas@clinicaromanorte.mx",
    phone: "5562881104",
    type: "Clinica",
    website: "",
    rating: "4.8",
    websiteStatus: "sin-sitio",
    source: "mock:cdmx-health-directory",
  },
  {
    name: "Bufete Fiscal Del Valle",
    city: "Ciudad de Mexico",
    email: "contacto@bfdelvalle.mx",
    phone: "5563991201",
    type: "Despacho",
    website: "",
    rating: "4.4",
    websiteStatus: "sin-sitio",
    source: "mock:cdmx-local-services",
  },
];

async function searchBusinesses(options = {}) {
  const requestedCities = Array.isArray(options.cities)
    ? options.cities.map((city) => normalizeName(city))
    : [];

  return mockBusinesses.filter((business) => {
    if (!requestedCities.length) {
      return true;
    }

    return requestedCities.includes(normalizeName(business.city));
  });
}

module.exports = {
  name: "mock",
  searchBusinesses,
};
